---
# tasks file for nginx
- name: Create a Service nginx
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: '{{ meta.name }}-nginx'
        namespace: '{{ meta.namespace }}'
      spec:
        type: ClusterIP
        selector:
          app: nginx
        ports:
        - protocol: TCP
          name: port-8080-tcp
          port: 8080

- name: start nginx
  community.kubernetes.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ meta.name }}-nginx-{{image_version}}'
        namespace: '{{ meta.namespace }}'
      spec:
        replicas: "{{size}}"
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
            - name: nginx
              image: "nginxinc/nginx-unprivileged:{{image_version}}"
              ports:
                - containerPort: 8080

