apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nginxes.webserver.example.com
spec:
  group: webserver.example.com
  names:
    kind: Nginx
    listKind: NginxList
    plural: nginxes
    singular: nginx
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
