kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ansible-operator-nginx-simple
subjects:
- kind: ServiceAccount
  name: ansible-operator-nginx-simple
roleRef:
  kind: Role
  name: ansible-operator-nginx-simple
  apiGroup: rbac.authorization.k8s.io
