name: Molecule Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]
        kube-version: [1.16, 1,17]

    steps:
      - uses: actions/checkout@v2
        with:
          path: molecule_demo
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install git apt-transport-https ca-certificates curl gnupg-agent software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible ansible-runner ansible-runner-http ansible-lint yamllint molecule molecule-docker openshift
          git clone  https://github.com/senyoltw/ansible-operator-nginx-simple
      - name: Test with molecule
        run: |
          cd ansible-operator-nginx-simple
          KUBE_VERSION=${{ matrix.kube-version }}
          molecule test -s test-local
